services:
  internet-map-backend:
    container_name: internet-map-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - internet-map
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: internet-map-nginx
    depends_on:
      - internet-map-backend
    ports:
      - "8080:8080"
    networks:
      - internet-map
    restart: unless-stopped

networks:
  internet-map:
    driver: bridge
